services:
  mongodb:
    image: "mongo"
    restart: unless-stopped
    volumes:
      - hd_data:/data/db
      - ./mongodb/docker-entrypoint-wrapper.sh:/docker-entrypoint-wrapper.sh:ro
    env_file:
      - .env.dev
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - hd_uploads:/app/uploads
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.dev
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    depends_on:
      - backend
  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    volumes:
      - ./telegram-bot:/app
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - mongodb
      - backend
volumes:
  hd_data:
    external: true
  hd_uploads:
    external: true
